version: '3'
services:
  testsamlidp_idp:
    build: .
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: jahia.sp.id
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost/cms/login.SAML.incoming
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost/cms/logout.SAML.incoming
      SIMPLESAMLPHP_ADMIN_PASSWORD: test
      SIMPLESAMLPHP_SECRET_SALT: salt
    ports:
    - "8081:8081"
    - "8444:8444"
    #volumes:
    #- /users.php:/var/www/simplesamlphp/config/simplesamlphp/authsources.php
